spring:
  h2:
    console.enabled: true
    console.settings.web-allow-others: true

  datasource:
    url: jdbc:h2:mem:lwin-emr
    username: admin
    password: dLlddP0v383P
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: create-drop

  sql:
    init:
      mode: always

logging:
  file.name: lwin-emr.log
  pattern.file: '%d %p %c{1.} [%t] %m%n'
  pattern.console: '%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n'
  level:
    root: DEBUG
    org.springframework.web: ERROR
